services:
  - type: web
    name: SAINITXT19 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/saini19028/Sainitxt19
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
